// Automatically generated by astro-icon
// 616f45982b45fd4123324348195120d80eff7e7844ca27da7b09efc7584a947f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa:graduation-cap"
		| "fa:heart"
		| "fa:linkedin"
		| "fa:github"
		| "fa:stack-overflow"
		| "fa:plane"
		| "fa:book"
		| "fa-solid:medal"
		| "fa-solid:award"
		| "fa-solid:basketball-ball"
		| "fa-solid:dumbbell";
}