// Automatically generated by astro-icon
// 4a06d85d82916696852cd1b893eb664ead0e346442bba452de2c0e230937c383

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa:graduation-cap"
		| "fa:heart"
		| "fa:linkedin"
		| "fa:github"
		| "fa:stack-overflow"
		| "fa:plane"
		| "fa:book"
		| "fa-solid:medal"
		| "fa-solid:award"
		| "fa-solid:basketball-ball";
}