language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: master
  keep-history: true
  on:
    branch: source

addons:
  sonarcloud:
    organization: "sjwilczynski"
    token: $sonarcloud_token

script:
  - npm run build
  - sonar-scanner
